@"
name: CI

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install python-docx regex streamlit

      - name: Run smoke build (no secrets)
        env:
          OPENAI_API_KEY: ""
        run: |
          python scripts/ci_smoke.py
"@ | Out-File -Encoding utf8 ".github\workflows\ci.yml"
